'use strict';
const english={
coordinationOwner:"Coordinated work · Shared research state",
stagePrepare:"Research & ideation",
stageOptimize:"Experiments & optimization",
stageWrite:"Writing & review",
coordinationFoundation:"Research workflows and domain methods, called on demand",
researchTitle:"Explore broadly. Read deeply. Think from evidence.",
researchDescription:"Map the field, then investigate the papers that matter. Turn consensus, disagreements, and open questions into candidate ideas, and use structured ideation and evaluation to find a question worth testing.",
breadthLabel:"BREADTH",
breadthDescription:"Map approaches, compare research directions, and identify unresolved gaps.",
depthLabel:"DEPTH",
depthDescription:"Use ArXiv MCP to retrieve and search full text. Keep versions and sources for the claims that matter.",
ideaLabel:"IDEATION",
ideaDescription:"Transfer ideas across fields, invert assumptions, and reframe problems. Check novelty, feasibility, and fatal flaws.",
ideasSource:"Explore the ideation methods ↗",
evidenceToIdea:"FROM PAPER EVIDENCE TO A TESTABLE IDEA",
ideaHandoff:"Evidence → candidate ideas → evaluation",
researchOutput:"Deliver: a sourced research brief, candidate directions, and an actionable research question.",
optimizationLabel:"OPTIMIZE FOR YOUR OBJECTIVE",
metricAccuracy:"Accuracy ↑",
metricLoss:"Loss ↓",
metricEfficiency:"Efficiency ↑",
experimentRange:"From hyperparameters to model architecture, execution, monitoring, queues, and watchdog skills connect individual trials into a continuous optimization workflow.",
dependencies:"LOCKED DEPENDENCIES",
packageLabel:"Build the task package",
executionLabel:"Run the autonomous loop",
loopBaseline:"Baseline first",
loopModify:"Propose & modify",
loopEvaluate:"Train & evaluate",
loopDecision:"Keep improvements · Revert regressions",
guardBudget:"Time budget",
guardRegression:"Regression guard",
guardNoise:"Noise rechecks",
guardLedger:"Git record",
optimizationNote:"Arrows indicate optimization goals, not measured gains. Results depend on the task, data, and budget. Choose comparable metrics for the task; keep a record of improvements, failures, and negative results.",
writingTitle:'Turn results into a paper that holds together.',writingDescription:'From judging the idea and building its structure to visual storytelling, citation checks, and dual review. Ground each claim in evidence. Give every figure a role in the argument.',writingSource:'Explore the paper-production pipeline ↗',paperIdea:'Idea & structure',paperNarrative:'Narrative & figures',paperDraft:'Drafting & verification',paperReview:'Evidence + writing review',paperGate:'Quality gates at every stage · Provenance & AI-use disclosure',
skip:'Skip to content',navWorkflow:'Workflow',navCapabilities:'Capabilities',navSkills:'Skills',navStart:'Get started',heroEyebrow:'LEMNIVO / AUTONOMOUS RESEARCH',heroLine1:'From an idea.',heroLine2:'To a discovery.',heroSub:'One research system. Two CLI engines.',heroDescription:"Lemnivo turns Claude Code and Codex CLI into autonomous research labs. Research Orchestrator coordinates literature and ideas, unattended model optimization, and paper writing and review, with 115 skills across nested experiment and reflection loops.",getStarted:'Start researching',seeLoop:'Watch the workflow',engineNote:'Two engines. One skill catalog.',demoLabel:'ILLUSTRATIVE',terminalPrompt:'Start a bounded, traceable research project',commitInit:'Frame the question · establish research state',commitProtocol:'Lock evaluation · commit before running',commitResults:'Modify → measure → keep / revert → log',commitReflect:'Synthesize findings · choose the next direction',terminalMemory:'findings.md · research that remembers',visualCaption:'Experiments move results. Reflection moves direction.',replay:'Replay ↺',metricSkills:'A shared research skill library',metricLoops:'Experiment + reflection',metricEngineUnit:' / engines',metricEngines:'Shared research foundations',metricDirectionUnit:' / directions',metricsSource:'Counted from repository SKILL.md files · 2026-10-07',checkSources:'View evidence ↗',
workflowTitle:"One orchestrator. The whole research journey.",workflowDescription:"Research Orchestrator coordinates literature, ideas, experiments, and writing. The inner loop optimizes and validates; the outer loop reflects and redirects, within your agreed goals and budget.",readSpec:'Read the workflow ↗',bootstrapTitle:'Ask a better question.',gate0:'An unclear idea → evidence-backed directions',gate1:'FINER review → scope and methodology',gatesNote:'Two gates are in the Codex edition. Gate 0 applies to unclear input.',outerLoop:'OUTER LOOP / SYNTHESIS & DIRECTION',synthesize:'Synthesize',askWhy:'Ask WHY',newHypothesis:'New hypotheses',innerLoop:'INNER LOOP / EXPERIMENT & VALIDATION',protocol:'Protocol',experiment:'Experiment',measure:'Measure',learn:'Learn',projectMemory:'Memory across sessions',finalizeTitle:'Make discovery durable.',output1:'Evidence & synthesis',output2:'Figures & progress reports',output3:'Paper drafts & archives',finalizeNote:'Conclude when evidence is sufficient. Negative results stay in the record.',directionHeading:'After the results, where next?',
capabilitiesTitle:"From a research question to a paper.",capabilitiesDescription:"Explore the question. Iterate on the model. Write from the evidence. Three stages, connected by a research workflow that remembers and reflects.",forgeTitle:"Give your model a task package built to iterate.",forgeDescription:"Experiment Forge turns your code and research goal into a Karpathy-style autonomous experiment package: locked evaluation, editable model code, and explicit budgets and rules. Autoresearch takes over to propose changes, train, evaluate, and keep or revert them—unattended, within agreed boundaries.",locked:"LOCKED DATA + EVAL",editable:"EDITABLE MODEL + TRAINING",contract:"GOAL, BUDGET & SCOPE",ledger:"RUN LEDGER",forgeSource:"Explore the autonomous task specification ↗",arxivTitle:'Ground the claim. Keep the evidence.',arxivDescription:'Search papers, retrieve full text, and locate evidence within it. Check load-bearing claims, record versions and provenance, and label what cannot be verified.',searchPapers:'Discover relevant work',downloadPaper:'Retrieve text & version',searchText:'Find & check the claim',traceable:'TRACEABLE',evidenceSource:'Explore the evidence conventions ↗',principleTitle:'Commit the protocol before running the experiment.',principleDescription:'Keep protocols and results in separate commits: a durable record that the plan preceded the run. Failed experiments and negative results belong here, too.',
skillsTitle:"115 skills. A method for every stage.",skillsDescription:"From AlphaFold2 to DeepSpeed, 115 research skills span literature, experiments, writing, and specialist methods. Orchestrator calls on the right expertise as the project needs it.",allSkills:'All skills',searchPlaceholder:'Find a skill, e.g. deepspeed',skillCategoriesNote:'12 curated topic groups · Open any skill to read its source',skillsFootnote:'One library of 115 research skills, adapted for Claude Code and Codex CLI. Counted from skills/*/SKILL.md files.',enginesTitle:'Your engine. A shared research mindset.',enginesDescription:'Shared research conventions and skill design, adapted for two CLIs. Use familiar tools to carry a research project from question to evidence.',claudeDescription:'115 skills and 4 specialist subagents. Native Claude Code agents, skills, and in-session heartbeats connect research, experiments, writing, and review.',codexDescription:'The same 115 skills, adapted for Codex CLI. Background experiments, completion markers, and project memory connect longer tasks.',
startTitle1:'Your next discovery.',startTitle2:'Starts in your terminal.',startDescription:'Install and sign in to your chosen CLI, then add research skills in a Bash environment. Existing configuration is backed up. Start a fresh session to begin.',startMeta:'Source available · Local workflows · Your compute',installLabel:'Install the research skills',copy:'Copy',installNote:'These three lines install skills and research conventions. Full-text retrieval needs a separate ArXiv MCP setup.',mcpSetup:'Set up ArXiv MCP full-text retrieval',mcpNote:'Requires Python and pip. Commands below use the default user installation path. Start Codex once first to create its configuration.',mcpCheck:'Restart the CLI and check that arxiv tools loaded. Adjust the command if you use a custom installation path.',firstPromptLabel:'THEN, GIVE IT YOUR FIRST QUESTION',firstPrompt:'Use research-orchestrator to start a project. My question is … and my budget is … . First establish the research plan and evaluation criteria.',
evidenceTitle:'Sources and demonstration notes',evidenceNote:'Skill counts checked on 2026-10-07: Claude b7aea95 and Codex 672b4a6, each with the same 115 skill names. The terminal animation illustrates the workflow. The 12 topic groups are editorial categories for this site.',autonomyNote:'Autonomous execution depends on an agreed question, a configured environment, a budget, and an active CLI session. The skill catalog is shared; execution mechanisms and some workflow details are adapted to each CLI. Researchers remain responsible for checking conclusions.',footerLine:'Autonomy for research. Evidence for discovery.',footerThanks:"Thanks to the open-source projects: "
};
const chinese={};document.querySelectorAll('[data-i18n]').forEach(el=>chinese[el.dataset.i18n]=el.textContent);chinese.searchPlaceholder='搜索技能，例如 deepspeed';
const $=id=>document.getElementById(id);let language='zh',direction='deepen',engine='all',install='claude',expanded=false;
try{if(localStorage.getItem('research-language')==='en')language='en'}catch{}
const urlLanguage=new URLSearchParams(location.search).get('lang');if(['en','zh'].includes(urlLanguage))language=urlLanguage;
const t=key=>(language==='en'?english:chinese)[key]??chinese[key]??key;
const directions={deepen:['深挖机制：把已经出现的信号，变成更具体、可验证的子假设。','Go deeper: turn an observed signal into a more specific, testable hypothesis.'],broaden:['拓宽问题：从已有结果出发，检验新的设置、任务或适用边界。','Broaden the question: test new settings, tasks, or boundaries suggested by the results.'],pivot:['重新定向：当假设被证伪，带着已经学到的事实回到 BOOTSTRAP。','Change direction: when a hypothesis fails, return to BOOTSTRAP with what the evidence taught you.'],conclude:['综合收尾：当证据与解释足以支撑发现，进入写作、报告与归档。','Bring it together: when evidence and explanation support a finding, move to writing, reporting, and archiving.']};
function setDirection(){document.querySelectorAll('[data-direction]').forEach(b=>{const active=b.dataset.direction===direction;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('direction-panel').textContent=directions[direction][language==='en'?1:0];$('direction-panel').setAttribute('aria-labelledby','direction-'+direction)}
function commands(){return `git clone https://github.com/Yichen-ZJU/${install}-for-research.git\ncd ${install}-for-research\nbash ${install==='claude'?'install.sh':'setup.sh install'}`}
function setInstall(){document.querySelectorAll('[data-install]').forEach(b=>{const active=b.dataset.install===install;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('install-panel').setAttribute('aria-labelledby','install-'+install);$('install-code').textContent=commands();$('mcp-code').textContent=install==='claude'?'python3 -m pip install --user arxiv-mcp-server\nclaude mcp add --scope user arxiv -- "$HOME/.local/bin/arxiv-mcp-server"':'python3 -m pip install --user arxiv-mcp-server\nbash scripts/register-arxiv-mcp.sh'}
function renderSkills(){
 const query=$('skill-search').value.trim().toLowerCase();const groups=window.RESEARCH_DATA.groups.map(g=>({...g,skills:g.skills.filter(s=>(engine==='all'||s[engine])&&(s.name.includes(query)||g.zh.includes(query)||g.en.toLowerCase().includes(query)))})).filter(g=>g.skills.length);const visible=(expanded||query)?groups:groups.slice(0,6);const total=groups.reduce((n,g)=>n+g.skills.length,0),shown=visible.reduce((n,g)=>n+g.skills.length,0);
 $('skills-count').textContent=language==='zh'?`${total} 个匹配技能 · 当前显示 ${shown} 个`:`${total} matching skills · ${shown} shown`;const fragment=document.createDocumentFragment();
 for(const g of visible){const article=document.createElement('article');article.className='skill-category';const header=document.createElement('div');header.className='category-header';const icon=document.createElement('i');icon.className='category-icon';icon.textContent=g.icon;icon.setAttribute('aria-hidden','true');const h=document.createElement('h3');h.textContent=g[language];const count=document.createElement('span');count.textContent=String(g.skills.length).padStart(2,'0');header.append(icon,h,count);const tags=document.createElement('div');tags.className='skill-tags';for(const s of g.skills){const a=document.createElement('a'),e=engine==='claude'?'claude':'codex';a.className='skill-tag';a.href=`https://github.com/Yichen-ZJU/${e}-for-research/blob/${window.RESEARCH_DATA.commits[e]}/skills/${s.name}/SKILL.md`;a.textContent=s.name;a.target='_blank';a.rel='noopener noreferrer';a.title=(s.claude?'Claude Code + Codex CLI':'Codex CLI')+' · SKILL.md';tags.append(a)}article.append(header,tags);fragment.append(article)}
 if(!total){const p=document.createElement('p');p.className='empty-skills';p.textContent=language==='zh'?'没有匹配的技能，试试其他关键词。':'No matching skills. Try another keyword.';fragment.append(p)}$('skill-grid').replaceChildren(fragment);$('show-skills').hidden=groups.length<=6||Boolean(query);$('show-skills').setAttribute('aria-expanded',String(expanded));$('show-skills').textContent=expanded?(language==='zh'?'收起技能库 ↑':'Show fewer skills ↑'):(language==='zh'?`展开全部 ${groups.length} 组技能 ↓`:`Explore all ${groups.length} topic groups ↓`)
}
function setLanguage(){document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=language==='zh'?'Lemnivo · 让想法，走到发现':'Lemnivo — From an idea to a discovery';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('language').textContent=language==='zh'?'EN ↗':'中文 ↗';$('language').setAttribute('aria-label',language==='zh'?'Switch to English':'切换到中文');$('skill-search').setAttribute('aria-label',language==='zh'?'搜索技能':'Search skills');document.querySelector('meta[name="description"]').content=t('heroDescription');document.querySelector('meta[property="og:title"]').content=document.title;document.querySelector('meta[property="og:description"]').content=t('heroDescription');document.querySelector('meta[name="twitter:title"]').content=document.title;document.querySelector('meta[name="twitter:description"]').content=t('heroDescription');setDirection();setInstall();renderSkills();document.dispatchEvent(new CustomEvent('research-language-change',{detail:{language}}))}
$('language').addEventListener('click',()=>{language=language==='zh'?'en':'zh';try{localStorage.setItem('research-language',language)}catch{}setLanguage()});
document.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>{direction=b.dataset.direction;setDirection()}));document.querySelectorAll('[data-install]').forEach(b=>b.addEventListener('click',()=>{install=b.dataset.install;setInstall()}));document.querySelectorAll('[data-engine]').forEach(b=>b.addEventListener('click',()=>{engine=b.dataset.engine;document.querySelectorAll('[data-engine]').forEach(a=>a.setAttribute('aria-pressed',String(a===b)));renderSkills()}));
for(const selector of ['[data-direction]','[data-install]']){const buttons=[...document.querySelectorAll(selector)];buttons.forEach((b,i)=>b.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%buttons.length;if(event.key==='ArrowLeft')next=(i+buttons.length-1)%buttons.length;if(event.key==='Home')next=0;if(event.key==='End')next=buttons.length-1;if(next!==undefined){event.preventDefault();buttons[next].click();buttons[next].focus()}}))}
$('skill-search').addEventListener('input',renderSkills);$('show-skills').addEventListener('click',()=>{expanded=!expanded;renderSkills();if(!expanded)$('skills').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!document.activeElement.isContentEditable){event.preventDefault();$('skill-search').focus()}});
let toastTimer;function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
$('copy-install').addEventListener('click',async()=>{let copied=false;try{await navigator.clipboard.writeText(commands());copied=true}catch{const field=document.createElement('textarea');field.value=commands();field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();try{copied=document.execCommand('copy')}catch{}field.remove();$('copy-install').focus()}toast(copied?(language==='zh'?'安装命令已复制':'Install commands copied'):(language==='zh'?'请选中命令后手动复制':'Please select and copy the commands manually'))});
let timers=[];function replay(){timers.forEach(clearTimeout);timers=[];const lines=[...document.querySelectorAll('[data-stage]')];if(matchMedia('(prefers-reduced-motion: reduce)').matches){lines.forEach(line=>line.classList.add('active'));return}lines.forEach(line=>line.classList.remove('active'));lines.forEach((line,i)=>timers.push(setTimeout(()=>line.classList.add('active'),300+i*750)))}$('replay').addEventListener('click',replay);setLanguage();replay();
